# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235797efe9928b1572fc5e45843aa685f92d19960a1192e1d41596375bcdd16885753d8f0b458afeb3bd3411a03b108646fe2b6538ec7f027f95ac6db6c33e38

test:
  secret_key_base: ad63dd8b0fab59953415c68743db59ae5ca3ffdb83ac3974f39fa4fff3fcb090b5c93f3b0df18e042f13a240004382f7b792be06591dae6bc2e7d1d79d91668a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
